name: Sphinx HTML generatie

on:
  push:
    branches: 
      - 'master'
#     paths:
#     - '!docs/**'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate HTML
      run: |
        sphinx-build -M html source/ build/
    - name: Update docs/
      run: |
        rm -rf docs/
        touch build/html/.nojekyll
    - name: Publiceer op GitHub Pages
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: build/html/
        GH_PAT: ${{ secrets.GH_PAT }}
